/* eslint-disable */
/* prettier-ignore-start */
/* auto-generated by @tanstack/router-generator — do not edit manually */

import { Route as rootRoute } from "./routes/__root"

import { Route as FailuresImport } from "./routes/failures"
import { Route as IndexImport } from "./routes/index"

const FailuresRoute = FailuresImport.update({
  id: "/failures",
  path: "/failures",
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any)

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/failures": {
      id: "/failures"
      path: "/failures"
      fullPath: "/failures"
      preLoaderRoute: typeof FailuresImport
      parentRoute: typeof rootRoute
    }
  }
}

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/failures": typeof FailuresRoute
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/failures": typeof FailuresRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  "/": typeof IndexRoute
  "/failures": typeof FailuresRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/failures"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/failures"
  id: "__root__" | "/" | "/failures"
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FailuresRoute: typeof FailuresRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FailuresRoute: FailuresRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */
/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/failures"
      ]
    },
    "/": {
      "filePath": "index.tsx",
      "parent": "__root__"
    },
    "/failures": {
      "filePath": "failures.tsx",
      "parent": "__root__"
    }
  }
}
ROUTE_MANIFEST_END */