import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import fs from "node:fs/promises";
import path from "node:path";

/**
 * Get swarm trace analysis data from the backend-generated JSON file
 */
export const getTraceAnalysis = createServerFn({ method: "GET" })
  .outputValidator(
    z.object({
      analysis_timestamp: z.number(),
      trace_count: z.number(),
      results: z.array(
        z.object({
          trace_index: z.number(),
          timestamp: z.number(),
          agent_count: z.number(),
          metrics: z.object({
            average_distance: z.number(),
            max_distance: z.number(),
            cluster_score: z.number(),
          }),
        })
      ),
    })
  )
  .handler(async () => {
    try {
      // Path to the JSON file generated by the backend
      // Uses TRACE_ANALYSIS_FILE env var or falls back to sensible default
      const filePath =
        process.env.TRACE_ANALYSIS_FILE ||
        path.resolve(process.cwd(), "../../swarm_trace_analysis.json");

      // Read and parse the JSON file
      const fileContents = await fs.readFile(filePath, "utf-8");
      const data = JSON.parse(fileContents);

      return data;
    } catch (error) {
      console.error("Error reading trace analysis file:", error);
      // Return demo data if file can't be read (fallback)
      return {
        analysis_timestamp: Date.now() / 1000,
        trace_count: 0,
        results: [],
      };
    }
  });

/**
 * Get a summary report of the trace analysis
 */
export const getTraceReport = createServerFn({ method: "GET" })
  .outputValidator(
    z.object({
      status: z.string(),
      trace_count: z.number(),
      average_agent_count: z.number(),
      min_cluster_score: z.number(),
      max_cluster_score: z.number(),
      average_cluster_score: z.number(),
      start_time: z.number(),
      end_time: z.number(),
    })
  )
  .handler(async () => {
    try {
      // Path to the JSON file generated by the backend
      // Uses TRACE_ANALYSIS_FILE env var or falls back to sensible default
      const filePath =
        process.env.TRACE_ANALYSIS_FILE ||
        path.resolve(process.cwd(), "../../swarm_trace_analysis.json");

      // Read and parse the JSON file
      const fileContents = await fs.readFile(filePath, "utf-8");
      const data = JSON.parse(fileContents);

      if (!data.results || data.results.length === 0) {
        return {
          status: "no_data",
          trace_count: 0,
          average_agent_count: 0,
          min_cluster_score: 0,
          max_cluster_score: 0,
          average_cluster_score: 0,
          start_time: 0,
          end_time: 0,
        };
      }

      const agentCounts = data.results.map((r: any) => r.agent_count);
      const clusterScores = data.results.map((r: any) => r.metrics.cluster_score);
      const timestamps = data.results.map((r: any) => r.timestamp);

      return {
        status: "complete",
        trace_count: data.results.length,
        average_agent_count:
          agentCounts.reduce((a: number, b: number) => a + b, 0) / agentCounts.length,
        min_cluster_score: Math.min(...clusterScores),
        max_cluster_score: Math.max(...clusterScores),
        average_cluster_score:
          clusterScores.reduce((a: number, b: number) => a + b, 0) / clusterScores.length,
        start_time: Math.min(...timestamps),
        end_time: Math.max(...timestamps),
      };
    } catch (error) {
      console.error("Error generating trace report:", error);
      return {
        status: "error",
        trace_count: 0,
        average_agent_count: 0,
        min_cluster_score: 0,
        max_cluster_score: 0,
        average_cluster_score: 0,
        start_time: 0,
        end_time: 0,
      };
    }
  });